env = Environment()

env['APP_TARGET'] = 'OniUserTracker'
env['APP_SOURCES'] = ['OniUserTracker.cpp']
env['DEBUG'] = 0

# CinderOni
env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')
