env = Environment()

env['APP_TARGET'] = 'OniBasicApp'
env['APP_SOURCES'] = ['OniBasicApp.cpp']

# CinderOni
env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')
