env = Environment()

env['APP_TARGET'] = 'NIBasicApp'
env['APP_SOURCES'] = ['NIBasicApp.cpp']

# Cinder-NI
env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')
