env = Environment()

env['APP_TARGET'] = 'OniStickman'
env['APP_SOURCES'] = ['OniStickman.cpp', 'Node.cpp']
env['DEBUG'] = 0

# CinderOni
env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')
