env = Environment()

env['APP_TARGET'] = 'NIUserContourApp'
env['APP_SOURCES'] = ['NIUserContourApp.cpp']

# Cinder-NI
env = SConscript('../../../scons/SConscript', exports = 'env')

# Cinder-OpenCV
env = SConscript('../../../../Cinder-OpenCV/scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')
